name: todlrtest
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.2
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  fpdart: ^1.1.0
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.7
  phosphor_flutter: ^2.0.0
  auto_size_text: ^3.0.0
  just_audio: ^0.9.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/vectors/
    - lib/assets/images/
    - lib/assets/audios/
